name: Run Unittests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        compiler: [clang++, g++]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install meson and gcovr
        run: pip3 install meson gcovr

      - name: Build using meson
        env:
          CXX: ${{ matrix.compiler }}
        run: meson --unity on -Dtests=enabled -Db_coverage=true build && ninja -C build

      - name: Run meson tests
        run: ninja -C build test

      - name: Generate Coverage
        run: ninja -C build coverage-xml

      - name: Upload Codecoverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: false
